'use strict';
const M=ImpactModel,D=IMPACT_DATA,$=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
let state=clone(D.defaults),rows=[],feeChangeMode='percent';
const money=x=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(x);
const rateMoney=x=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(x);
const percent=x=>(Math.round(x*1000+1e-8)/10).toFixed(1)+'%';
const signed=(x,formatter)=>Math.abs(x)<1e-10?formatter(0):(x>0?'+':'−')+formatter(Math.abs(x));
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shortUse=x=>x.replace('Residential (per housing unit) - ','Housing: ');
const factor=()=>Number($('period').value)/D.historicalYears;
const revenueCategories=[
 {name:'Residential',color:'#f2c94c',text:'#172b3a'},
 {name:'Customer-Oriented High',color:'#a8202d',text:'#fff'},
 {name:'Customer-Oriented Moderate',color:'#d54b55',text:'#fff'},
 {name:'Customer-Oriented Low',color:'#f29c9c',text:'#172b3a'},
 {name:'Industrial',color:'#7b4e9d',text:'#fff'},
 {name:'Warehouse/Distribution',color:'#ab86c2',text:'#172b3a'},
 {name:'Office',color:'#286aaf',text:'#fff'},
 {name:'Institutional',color:'#8bb7de',text:'#172b3a'},
 {name:'Lodging',color:'#e58a2b',text:'#172b3a'},
 {name:'Other',color:'#abb3ba',text:'#172b3a'}
];
const chartCategory=r=>r.use.startsWith('Residential')?'Residential':revenueCategories.some(c=>c.name===r.use)?r.use:'Other';
function revenueComposition(items){const totals=M.total(items),f=factor();return {current:totals.current*f,proposed:totals.proposed*f,segments:revenueCategories.map(c=>{const value=items.filter(r=>chartCategory(r)===c.name).reduce((sum,r)=>sum+r.proposed,0)*f;return {...c,value,share:totals.proposed?value/(totals.proposed*f):0};})};}
const compactMoney=x=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1}).format(x);
function chartScale(max){if(max<=0)return 1;const magnitude=10**Math.floor(Math.log10(max)),normalized=max/magnitude;return (normalized<=1?1:normalized<=2?2:normalized<=2.5?2.5:normalized<=5?5:10)*magnitude;}
function revenueChart(c,scale,label){const segments=c.segments.filter(s=>s.value>0).map(s=>{const height=s.value/scale*100,detail=s.name+': '+money(s.value)+' · '+percent(s.share)+' of proposed revenue';return `<div class="revenue-segment" tabindex="0" style="height:${height}%;background:${s.color};color:${s.text}" data-chart-category="${esc(s.name)}" data-chart-scope="${esc(label)}" data-chart-amount="${money(s.value)}" data-chart-share="${percent(s.share)}" aria-label="${esc(detail)}"></div>`;}).join('');return `<div class="comparison-chart" role="group" aria-label="${esc(label+': current revenue '+money(c.current)+', proposed revenue '+money(c.proposed))}"><div class="chart-axis" aria-hidden="true">${[1,.75,.5,.25,0].map(t=>`<span>${compactMoney(scale*t)}</span>`).join('')}</div><div class="bar-plot"><div class="revenue-bar current-revenue-bar" style="height:${c.current/scale*100}%" title="${esc('Current revenue: '+money(c.current))}" aria-label="${esc('Current revenue: '+money(c.current))}"></div><div class="revenue-bar proposed-revenue-bar" aria-label="Proposed revenue by land use">${segments}</div></div></div>`;}
function renderRevenueCharts(){hideRevenueTooltip();const city=revenueComposition(rows),benefits=Object.keys(D.defaults.benefit).map(name=>({name,...revenueComposition(rows.filter(r=>r.benefit===name))})),benefitScale=chartScale(Math.max(...benefits.flatMap(c=>[c.current,c.proposed])));$('city-revenue-chart').innerHTML=revenueChart(city,chartScale(Math.max(city.current,city.proposed)),'Citywide');$('benefit-revenue-charts').innerHTML=benefits.map(c=>`<section class="benefit-chart"><h4>${esc(c.name)}</h4>${revenueChart(c,benefitScale,c.name)}<div class="chart-bar-labels"><span>Current</span><span>Proposed</span></div></section>`).join('');$('benefit-revenue-summary').innerHTML=benefits.map(c=>{const delta=c.proposed-c.current;return `<tr><th scope="row">${esc(c.name)}</th><td>${money(c.current)}</td><td>${money(c.proposed)}</td><td>${signed(delta,money)}</td></tr>`;}).join('');$('revenue-chart-legend').innerHTML=city.segments.filter(s=>s.value>0).map(s=>`<span class="revenue-legend-item" title="${esc(s.name+': '+money(s.value)+' proposed revenue')}"><i style="background:${s.color}" aria-hidden="true"></i><span>${esc(s.name)}</span></span>`).join('');}
let activeRevenueSegment=null;
function hideRevenueTooltip(){if(activeRevenueSegment)activeRevenueSegment.removeAttribute('aria-describedby');activeRevenueSegment=null;$('revenue-chart-tooltip').hidden=true;}
function positionRevenueTooltip(e,target){const tip=$('revenue-chart-tooltip'),rect=target.getBoundingClientRect(),pointer=Number.isFinite(e.clientX)&&Number.isFinite(e.clientY),x=pointer?e.clientX:rect.left+rect.width/2,y=pointer?e.clientY:rect.bottom,size=tip.getBoundingClientRect(),width=document.documentElement.clientWidth,height=document.documentElement.clientHeight;const left=Math.max(8,Math.min(x+14,width-size.width-8)),top=y+14+size.height>height?Math.max(8,y-size.height-14):y+14;tip.style.left=left+'px';tip.style.top=top+'px';}
function showRevenueTooltip(e){const target=e.target.closest('[data-chart-category]');if(!target)return;const data=target.dataset,tip=$('revenue-chart-tooltip');if(activeRevenueSegment&&activeRevenueSegment!==target)activeRevenueSegment.removeAttribute('aria-describedby');activeRevenueSegment=target;tip.innerHTML=`<strong>${esc(data.chartCategory)}</strong><span class="tooltip-scope">${esc(data.chartScope)} · Proposed</span><div><span>Revenue</span><b>${esc(data.chartAmount)}</b></div><div><span>Share</span><b>${esc(data.chartShare)}</b></div>`;target.setAttribute('aria-describedby','revenue-chart-tooltip');tip.hidden=false;positionRevenueTooltip(e,target);}
for(const id of ['city-revenue-chart','benefit-revenue-charts']){const root=$(id);root.onpointerover=showRevenueTooltip;root.onpointermove=e=>{if(activeRevenueSegment)positionRevenueTooltip(e,activeRevenueSegment);};root.onpointerout=e=>{if(activeRevenueSegment&&e.relatedTarget?.closest('[data-chart-category]')!==activeRevenueSegment)hideRevenueTooltip();};root.onpointerleave=hideRevenueTooltip;root.onfocusin=showRevenueTooltip;root.onfocusout=hideRevenueTooltip;root.onclick=showRevenueTooltip;root.onkeydown=e=>{if(e.key==='Escape')hideRevenueTooltip();};}
function validInput(el){if(el.value.trim()===''||!el.checkValidity()||!Number.isFinite(Number(el.value))){$('status').textContent='Enter a discount between 0 and 100%.';return false;}$('status').textContent='';return true;}
function controls(){for(const [key,id] of [['sector','sector-discounts'],['benefit','benefit-discounts']]){const container=$(id);container.replaceChildren();for(const [index,name] of Object.keys(D.defaults[key]).entries()){const row=document.createElement('div');row.className='discount-head geographic-discount';const label=document.createElement('label');label.textContent=name;const pair=document.createElement('div');const input=document.createElement('input');input.type='number';input.min=0;input.max=100;input.step=.5;input.value=state[key][name];input.id=id+'-'+index;label.setAttribute('for',input.id);input.setAttribute('aria-label',name+' '+key+' discount percent');const symbol=document.createElement('span');symbol.textContent='%';pair.append(input,symbol);row.append(label,pair);input.oninput=()=>{if(validInput(input)){state[key][name]=Number(input.value);render();}};container.append(row);}}
 activityTables();}
const tabNames=['fees','discounts','activity','revenue','phase'],panelIds={fees:'fee-panel',discounts:'discount-panel',activity:'activity-panel',revenue:'revenue-panel',phase:'phase-panel'};
function selectTab(name){for(const tab of tabNames){const selected=tab===name;$(panelIds[tab]).hidden=!selected;$('tab-'+tab).setAttribute('aria-selected',String(selected));$('tab-'+tab).setAttribute('tabindex',selected?'0':'-1');}$('fee-filters').hidden=name!=='fees';}
function tabKeys(e){if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const index=tabNames.indexOf(e.currentTarget.id.replace('tab-','')),next=e.key==='Home'?0:e.key==='End'?tabNames.length-1:(index+(e.key==='ArrowRight'?1:-1)+tabNames.length)%tabNames.length;selectTab(tabNames[next]);$('tab-'+tabNames[next]).focus();}
for(const name of tabNames){$('tab-'+name).onclick=()=>selectTab(name);$('tab-'+name).onkeydown=tabKeys;}
function initLocation(){const options=Object.keys(D.defaults.sector).map(x=>`<option>${esc(x)}</option>`).join('');for(const id of ['fee-sector','activity-sector','phase-sector']){$(id).innerHTML=options;$(id).value='Northeast';}$('fee-sector').onchange=()=>feeTables();$('activity-sector').onchange=activityTables;$('revenue-sector').innerHTML='<option value="all">Citywide</option>'+options;$('revenue-sector').value='all';revenueBenefits();$('revenue-sector').onchange=()=>{revenueBenefits();revenueTables();};$('revenue-benefit').onchange=revenueTables;phaseBenefits();$('phase-sector').onchange=()=>{phaseBenefits();phaseTables();};$('phase-benefit').onchange=phaseTables;}
function locationData(selector='fee-sector'){const sector=$(selector).value,local=D.feeSchedules.filter(r=>r.sector===sector),benefits=[...new Set(local.map(r=>r.benefit))];const names=[...new Set(D.feeSchedules.map(r=>r.use))].sort((a,b)=>Number(a.startsWith('Residential'))-Number(b.startsWith('Residential'))||(a.startsWith('Residential')&&b.startsWith('Residential')?D.feeSchedules.find(r=>r.use===a).sampleSf-D.feeSchedules.find(r=>r.use===b).sampleSf:a.localeCompare(b,undefined,{numeric:true})));return {sector,local,benefits,names};}
function feeFor(r){return r&&r.phase2Rate!==null?M.feeCost(r,state,r.residential?r.sampleSf:1000):null;}
function currentRate(use,benefit){let cat=use.startsWith('Residential')?'Residential':['Industrial','Warehouse/Distribution'].includes(use)?'Industrial':['Office','Institutional','Lodging'].includes(use)?'Office':{'Customer-Oriented Low':'Customer Low','Customer-Oriented Moderate':'Customer Moderate','Customer-Oriented High':'Customer High'}[use];return D.currentFeeSchedule[benefit][cat]*(1+state.baselineCpi/100);}
function tableUseNames(residential){return [...new Set(D.feeSchedules.filter(r=>r.residential===residential).map(r=>r.use))];}
function syncTableDiscounts(){for(const [prefix,residential] of [['nonres',false],['res',true]]){const values=tableUseNames(residential).map(name=>state.use[name]),same=values.every(v=>v===values[0]),number=$(prefix+'-discount-number'),slider=$(prefix+'-discount-range');if(same){if(number.value.trim()===''||Number(number.value)!==values[0])number.value=values[0];number.setAttribute('placeholder','');slider.value=values[0];slider.setAttribute('aria-valuetext',values[0]+'%');}else{number.value='';number.setAttribute('placeholder','Mixed');slider.value=values.reduce((sum,v)=>sum+v,0)/values.length;slider.setAttribute('aria-valuetext','Mixed discounts');}}}
function applyTableDiscount(input,residential){if(!validInput(input))return;const value=Number(input.value);for(const name of tableUseNames(residential))state.use[name]=value;render();}
for(const [prefix,residential] of [['nonres',false],['res',true]])for(const suffix of ['range','number']){const input=$(prefix+'-discount-'+suffix);input.oninput=()=>applyTableDiscount(input,residential);}
function feeTables(updateOnly=false){syncTableDiscounts();const {local,benefits,names}=locationData(),showChange=$('show-fee-change').checked,showMax=$('show-fee-max').checked;
 const pair=(current,proposed,maximum)=>{const cents=x=>Math.round(x*100+1e-8),direction=proposed===null?'fee-missing':cents(proposed)>cents(current)?'fee-increase':cents(proposed)<cents(current)?'fee-decrease':'fee-unchanged';let change='';if(showChange&&proposed!==null){const amount=feeChangeMode==='dollar'?(direction==='fee-unchanged'?rateMoney(0):signed(proposed-current,rateMoney)):(direction==='fee-unchanged'?'0.0%':current===0?'n/a':signed((proposed-current)/current,percent));change=` <span class="fee-change-separator">|</span> <span class="fee-change">(${amount})</span>`;}return `<div class="fee-pair">${showMax?`<span class="paired-maximum">${rateMoney(maximum)}</span> | `:''}<span class="paired-current">${rateMoney(current)}</span> | <span class="paired-proposed ${direction}">${proposed===null?'<span class="missing-label">Not provided</span>':rateMoney(proposed)+change}</span></div>`;};
 const header=isRes=>'<thead><tr><th scope="col">'+(isRes?'Dwelling size':'Land use')+'</th><th scope="col" class="discount-column">Discount</th>'+benefits.map(b=>`<th scope="col">${esc(b)}<small class="pair-key">${showMax?'Maximum | ':''}Current | <span class="paired-proposed">Proposed${showChange?' | '+(feeChangeMode==='dollar'?'$ change':'% change'):''}</span></small></th>`).join('')+'</tr></thead>';
 for(const isRes of [false,true]){const selected=names.filter(name=>D.feeSchedules.find(r=>r.use===name).residential===isRes);const body=selected.map((name,useIndex)=>{const representative=D.feeSchedules.find(r=>r.use===name);return `<tr><td>${esc(isRes?name.replace('Residential (per housing unit) - ',''):name)}</td><td class="discount-cell"><div class="table-discount"><input type="number" min="0" max="100" step="0.5" value="${state.use[name]}" data-use="${esc(name)}" aria-label="${esc(name)} discount percent"><span>%</span></div></td>`+benefits.map((benefit,benefitIndex)=>{const r=local.find(r=>r.use===name&&r.benefit===benefit),f=feeFor(r),currentSf=currentRate(name,benefit),current=isRes?currentSf*representative.sampleSf:currentSf,proposed=f?(isRes?f.proposedPerUnit:f.proposedPerSf):null;const missing='<span class="missing-label">Not provided</span>';const unit=isRes?'per dwelling':'per square foot';const label=`${name}, ${benefit}: ${showMax?'maximum supportable '+rateMoney(isRes?f.supportablePerUnit:f.supportablePerSf)+' '+unit+', ':''}current ${rateMoney(current)} ${unit}, proposed ${proposed===null?'not provided':rateMoney(proposed)+' '+unit}`;const cellId=`fee-value-${isRes?'res':'nonres'}-${useIndex}-${benefitIndex}`,value=pair(current,proposed,isRes?f.supportablePerUnit:f.supportablePerSf);if(updateOnly){$(cellId).innerHTML=value;$(cellId).setAttribute('aria-label',label);}return `<td id="${cellId}" aria-label="${esc(label)}">${value}</td>`;}).join('')+'</tr>';}).join('');if(!updateOnly)$(isRes?'residential-fee-schedule':'fee-schedule').innerHTML=`<caption class="sr-only">${isRes?'Residential per dwelling':'Nonresidential per square foot'} current and proposed fees for ${esc($('fee-sector').value)}</caption>`+header(isRes)+'<tbody>'+body+'</tbody>';}}
const activityNumber=x=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(x);
function activityTables(){const {sector,local,benefits,names}=locationData('activity-sector'),unlocked=$('unlock-activity').checked;$('restore-activity').disabled=!unlocked;for(const isRes of [false,true]){const selected=names.filter(name=>name.startsWith('Residential')===isRes);$(isRes?'activity-residential':'activity-nonresidential').innerHTML=`<caption class="sr-only">Five-year modeled ${isRes?'dwellings':'square footage'} and annualized development for ${esc(sector)}</caption><thead><tr><th scope="col">${isRes?'Dwelling size':'Land use'}</th>${benefits.map(b=>`<th scope="col">${esc(b)}<small class="activity-period-head"><span>5-year</span><span>Annualized</span></small></th>`).join('')}</tr></thead><tbody>`+selected.map((name,useIndex)=>`<tr><td>${esc(name.replace('Residential (per housing unit) - ',''))}</td>`+benefits.map((benefit,benefitIndex)=>{const r=local.find(r=>r.use===name&&r.benefit===benefit),key=M.activityKey(r),quantity=isRes?state.activity[key]/r.sampleSf:state.activity[key],id=`activity-input-${isRes?'res':'nonres'}-${useIndex}-${benefitIndex}`,annual=`activity-annual-${isRes?'res':'nonres'}-${useIndex}-${benefitIndex}`,unit=isRes?'dwellings':'square footage';return `<td><div class="activity-period-pair"><div><input id="${id}" class="activity-input" type="number" min="0" step="any" value="${Number(quantity.toFixed(2))}" data-activity="${esc(key)}" data-annual="${annual}" aria-label="${esc(name+', '+benefit+', '+sector+' five-year modeled '+unit)}" ${unlocked?'':'disabled'}></div><div><output id="${annual}" class="activity-annual" aria-label="${esc(name+', '+benefit+', '+sector+' annualized '+unit+' per year')}">${activityNumber(quantity/D.historicalYears)}</output></div></div></td>`;}).join('')+'</tr>').join('')+'</tbody>';}}
function activityInput(e){const input=e.target,key=input.dataset.activity;if(!$('unlock-activity').checked||!Object.hasOwn(state.activity,key))return;const r=D.feeSchedules.find(row=>M.activityKey(row)===key),quantity=Number(input.value),area=r.residential?quantity*r.sampleSf:quantity;if(input.value.trim()===''||!input.checkValidity()||!Number.isFinite(quantity)||!Number.isFinite(area)||quantity<0){$('activity-status').textContent=r.residential?'Enter a dwelling count of zero or more.':'Enter square footage of zero or more.';return;}$('activity-status').textContent='';state.activity[key]=area;$(input.dataset.annual).textContent=activityNumber(quantity/D.historicalYears);render();}
function tableDiscountInput(e){const input=e.target,name=input.dataset.use;if(!Object.hasOwn(state.use,name))return;if(validInput(input)){state.use[name]=Number(input.value);render(true);}}
$('activity-nonresidential').oninput=activityInput;$('activity-residential').oninput=activityInput;$('unlock-activity').onchange=()=>{$('activity-status').textContent='';activityTables();};$('restore-activity').onclick=()=>{if(!$('unlock-activity').checked)return;state.activity=clone(D.defaults.activity);$('activity-status').textContent='';activityTables();render();};
function revenueBenefits(){const sector=$('revenue-sector').value,old=$('revenue-benefit').value,benefits=[...new Set(D.feeSchedules.filter(r=>sector==='all'||r.sector===sector).map(r=>r.benefit))];$('revenue-benefit').innerHTML='<option value="all">All areas</option>'+benefits.map(b=>`<option>${esc(b)}</option>`).join('');$('revenue-benefit').value=benefits.includes(old)?old:'all';}
function revenueTables(){const sector=$('revenue-sector').value,benefit=$('revenue-benefit').value,local=rows.filter(r=>(sector==='all'||r.sector===sector)&&(benefit==='all'||r.benefit===benefit)),names=locationData().names;
 const pair=(current,proposed)=>{const direction=Math.round(proposed+1e-8)>Math.round(current+1e-8)?'fee-increase':Math.round(proposed+1e-8)<Math.round(current+1e-8)?'fee-decrease':'fee-unchanged';return `<div class="fee-pair"><span class="paired-current">${money(current)}</span> | <span class="paired-proposed ${direction}">${money(proposed)}</span></div>`;};
 for(const isRes of [false,true]){const selected=names.filter(name=>name.startsWith('Residential')===isRes),selectedRows=local.filter(r=>selected.includes(r.use)),grouped=new Map(M.groups(selectedRows,'use').map(g=>[g.name,g])),totals=M.total(selectedRows),scope=(sector==='all'?'Citywide':sector)+', '+(benefit==='all'?'all areas':benefit);const cells=t=>`<td aria-label="${esc('Five-year current '+money(t.current)+', proposed '+money(t.proposed))}">${pair(t.current,t.proposed)}</td><td aria-label="${esc('Annualized current '+money(t.current/D.historicalYears)+', proposed '+money(t.proposed/D.historicalYears))}">${pair(t.current/D.historicalYears,t.proposed/D.historicalYears)}</td>`;
 $(isRes?'revenue-residential':'revenue-nonresidential').innerHTML=`<caption class="sr-only">${isRes?'Residential':'Nonresidential'} modeled revenue: ${esc(scope)}</caption><thead><tr><th scope="col">${isRes?'Dwelling size':'Land use'}</th><th scope="col">5-year total<small class="pair-key">Current | Proposed</small></th><th scope="col">Annualized<small class="pair-key">Current | Proposed</small></th></tr></thead><tbody>`+selected.map(name=>`<tr><td>${esc(name.replace('Residential (per housing unit) - ',''))}</td>${cells(grouped.get(name)||{current:0,proposed:0})}</tr>`).join('')+`</tbody><tfoot><tr><th scope="row">Subtotal</th>${cells(totals)}</tr></tfoot>`;}}
function phaseBenefits(){const {benefits}=locationData('phase-sector'),old=$('phase-benefit').value;$('phase-benefit').innerHTML=benefits.map(b=>`<option>${esc(b)}</option>`).join('');$('phase-benefit').value=benefits.includes(old)?old:benefits[0];}
function phaseRows(){const {sector,local,names}=locationData('phase-sector'),benefit=$('phase-benefit').value;return names.map(name=>{const r=local.find(r=>r.use===name&&r.benefit===benefit),f=feeFor(r),current=r.residential?f.baselinePerSf*r.sampleSf:f.baselinePerSf,proposed=r.residential?f.proposedPerUnit:f.proposedPerSf;return {name,sector,benefit,residential:r.residential,...M.phaseIn(current,proposed)};});}
function phaseTables(){const items=phaseRows(),years=items[0].schedule.map(s=>s.year);for(const isRes of [false,true]){$(isRes?'phase-residential':'phase-nonresidential').innerHTML=`<caption class="sr-only">${isRes?'Residential fees per dwelling':'Nonresidential fees per square foot'} phased in at 15% annually from 2027 through 2037, no inflation, ${esc($('phase-sector').value)}, ${esc($('phase-benefit').value)}</caption><thead><tr><th scope="col">${isRes?'Dwelling size':'Land use'}</th><th scope="col">Steps</th><th scope="col">Full fee year</th><th scope="col">Proposed</th>${years.map(year=>`<th scope="col">${year}${year===2027?'<small class="pair-key">Current</small>':''}</th>`).join('')}</tr></thead><tbody>`+items.filter(r=>r.residential===isRes).map(r=>`<tr><td>${esc(r.name.replace('Residential (per housing unit) - ',''))}</td><td>${r.steps===null?'N/A':r.steps}</td><td>${r.reachedYear===null?'Not reached':r.reachedYear}</td><td>${rateMoney(r.proposed)}</td>`+r.schedule.map(s=>`<td aria-label="${esc(r.name+', '+s.year+': '+rateMoney(s.value)+(s.atTarget?', proposed fee reached':''))}">${rateMoney(s.value)}</td>`).join('')+'</tr>').join('')+'</tbody>';}}

function render(preserveFeeInputs=false){rows=M.calculate(D,state);const t=M.total(rows),f=factor();$('current').textContent=money(t.current*f);$('proposed').textContent=money(t.proposed*f);const difference=Math.round(t.delta*f);$('delta').textContent=signed(difference,money);$('delta').className=difference>0?'difference-positive':difference<0?'difference-negative':'difference-zero';renderRevenueCharts();feeTables(preserveFeeInputs);revenueTables();phaseTables();}
function changeMode(mode){feeChangeMode=mode;$('change-percent').setAttribute('aria-pressed',String(mode==='percent'));$('change-dollar').setAttribute('aria-pressed',String(mode==='dollar'));feeTables();}
$('change-percent').onclick=()=>changeMode('percent');$('change-dollar').onclick=()=>changeMode('dollar');
$('fee-schedule').oninput=tableDiscountInput;$('residential-fee-schedule').oninput=tableDiscountInput;
$('show-fee-max').onchange=()=>feeTables();$('show-fee-change').onchange=()=>feeTables();$('period').onchange=()=>render();
$('reset').onclick=()=>{state=clone(D.defaults);$('status').textContent='';controls();render();};$('zero').onclick=()=>{state.globalDiscount=0;for(const key of ['sector','benefit','use'])for(const name of Object.keys(state[key]))state[key][name]=0;controls();render();};
$('unlock-activity').checked=false;
$('show-fee-max').checked=false;$('show-fee-change').checked=false;selectTab('fees');initLocation();controls();render();
