// Exercise app event handlers and output generation in a minimal DOM harness.
// This verifies behavior, not browser layout or accessibility.
const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
class Element{
 constructor(tag='div'){this.tag=tag;this.children=[];this.attributes={};this._value='';this._html='';this.textContent='';this.dataset={};this.style={};}
 set value(v){this._value=String(v);}get value(){return this._value;}
 set innerHTML(v){this._html=v;if(this.tag==='select'){const m=v.match(/<option(?: value="([^"]*)")?[^>]*>([^<]*)<\/option>/);this.value=m?(m[1]??m[2]):'';}if(this.tag==='table'){this.children=[];for(const match of v.matchAll(/<td id="([^"]+)"[^>]*>([\s\S]*?)<\/td>/g)){const el=new Element('td');el._html=match[2];ids[match[1]]=el;}for(const match of v.matchAll(/<input\b[^>]*>/g)){const input=new Element('input');const attr=name=>match[0].match(new RegExp('\\b'+name+'="([^"]*)"'))?.[1];for(const name of ['value','min','max','step','type','id'])if(attr(name)!==undefined)input[name]=attr(name);for(const [name,key] of [['data-use','use'],['data-activity','activity'],['data-equivalent','equivalent'],['data-annual','annual'],['data-annual-equivalent','annualEquivalent']])if(attr(name)!==undefined)input.dataset[key]=attr(name);input.disabled=/\bdisabled\b/.test(match[0]);if(input.id)ids[input.id]=input;this.children.push(input);}for(const match of v.matchAll(/<output id="([^"]+)"[^>]*>([^<]*)<\/output>/g)){const el=new Element('output');el.textContent=match[2];ids[match[1]]=el;}for(const match of v.matchAll(/<small id="([^"]+)"[^>]*>([^<]*)<\/small>/g)){const el=new Element('small');el.textContent=match[2];ids[match[1]]=el;}}}get innerHTML(){return this.tag==='table'?this._html.replace(/(<td id="([^"]+)"[^>]*>)[\s\S]*?(<\/td>)/g,(_,open,id,close)=>open+ids[id]._html+close):this._html;}
 append(...items){this.children.push(...items);}replaceChildren(){this.children=[];}
 setAttribute(k,v){this.attributes[k]=v;}
 removeAttribute(k){delete this.attributes[k];}
 getBoundingClientRect(){return {left:100,top:100,bottom:140,width:230,height:120};}
 closest(){return this.dataset.chartCategory?this:null;}
 checkValidity(){const n=Number(this.value);return this.value!==''&&Number.isFinite(n)&&n>=Number(this.min??-Infinity)&&n<=Number(this.max??Infinity);}
 click(){} focus(){this.focused=true;} }
const body=fs.readFileSync(__dirname+'/body.html','utf8'),ids={};for(const match of body.matchAll(/<(\w+)[^>]*\bid="([^"]+)"[^>]*>/g)){const el=new Element(match[1]);const val=match[0].match(/\bvalue="([^"]*)"/);if(val)el.value=val[1];for(const name of ['min','max','step','type']){const attr=match[0].match(new RegExp('\\b'+name+'="([^"]*)"'));if(attr)el[name]=attr[1];}el.checked=/\bchecked\b/.test(match[0]);ids[match[2]]=el;}
ids.period.value='1';
const data=JSON.parse(fs.readFileSync(__dirname+'/data.json'));
const context=vm.createContext({document:{documentElement:{clientWidth:1024,clientHeight:768},getElementById:id=>{assert.ok(ids[id],`Missing DOM id ${id}`);return ids[id];},createElement:tag=>new Element(tag)},IMPACT_DATA:data,localStorage:{getItem:()=>null,setItem:()=>{}},Intl,Blob,URL,setTimeout,console});
vm.runInContext(fs.readFileSync(__dirname+'/model.js','utf8'),context);vm.runInContext(fs.readFileSync(__dirname+'/app.js','utf8'),context);
const visible=id=>ids[id].innerHTML.replace(/<[^>]*>/g,'');
const useInput=name=>['fee-schedule','residential-fee-schedule'].flatMap(id=>ids[id].children).find(input=>input.dataset.use===name);
const editUse=input=>ids[input.dataset.use.startsWith('Residential')?'residential-fee-schedule':'fee-schedule'].oninput({target:input});
assert.equal(ids.current.textContent,'$6,596,969');assert.equal(ids.proposed.textContent,'$7,118,442');assert.ok(visible('fee-schedule').includes('$2.51 | $5.79'));assert.ok(ids['fee-schedule'].innerHTML.includes('paired-proposed'));assert.ok(!ids['fee-schedule'].innerHTML.includes('Housing:'));assert.ok(!ids['residential-fee-schedule'].innerHTML.includes('Customer-Oriented'));
if(process.env.IMPACT_SNAPSHOT_PATH)fs.writeFileSync(process.env.IMPACT_SNAPSHOT_PATH,JSON.stringify({table:ids['fee-schedule'].innerHTML,residentialTable:ids['residential-fee-schedule'].innerHTML,current:ids.current.textContent,proposed:ids.proposed.textContent,delta:ids.delta.textContent,deltaClass:ids.delta.className,activityNonres:ids['activity-nonresidential'].innerHTML,activityRes:ids['activity-residential'].innerHTML,revenueNonres:ids['revenue-nonresidential'].innerHTML,revenueRes:ids['revenue-residential'].innerHTML,phaseNonres:ids['phase-nonresidential'].innerHTML,phaseRes:ids['phase-residential'].innerHTML,cityChart:ids['city-revenue-chart'].innerHTML,benefitCharts:ids['benefit-revenue-charts'].innerHTML,chartLegend:ids['revenue-chart-legend'].innerHTML,benefitSummary:ids['benefit-revenue-summary'].innerHTML}));
assert.equal(ids['show-fee-change'].checked,false);assert.equal(ids['show-fee-max'].checked,false);assert.ok(body.indexOf('id="show-fee-max"')<body.indexOf('id="show-fee-change"'));assert.ok(body.indexOf('id="show-fee-change"')<body.indexOf('id="fee-sector"'));
assert.ok(!ids['fee-schedule'].innerHTML.includes('paired-maximum'));assert.ok(!ids['fee-schedule'].innerHTML.includes('fee-change'));
ids['show-fee-change'].checked=true;ids['show-fee-change'].onchange();assert.ok(visible('fee-schedule').includes('$2.51 | $5.79 | (+130.5%)'));
assert.ok(ids['residential-fee-schedule'].innerHTML.split('<tbody>')[1].startsWith('<tr><td>Under 1,000</td>'));assert.ok(!ids['residential-fee-schedule'].innerHTML.includes('sq ft example'));
const baseline=ids.current.textContent,initial=ids.proposed.textContent;
let input=useInput('Customer-Oriented High');input.value=90;editUse(input);assert.equal(ids.current.textContent,baseline);assert.notEqual(ids.proposed.textContent,initial);assert.equal(useInput(input.dataset.use),input);
let control=ids['sector-discounts'].children[0],num=control.children[1].children[0];num.value=100;num.oninput();assert.equal(ids.current.textContent,baseline);
ids['fee-sector'].value='Core';ids['fee-sector'].onchange();assert.ok(visible('fee-schedule').includes('$2.19 | $0.00'));
ids.reset.onclick();assert.equal(ids.proposed.textContent,initial);assert.ok(visible('fee-schedule').includes('$2.19 | $2.27'));assert.ok(visible('residential-fee-schedule').includes('$400.00 | $315.00 | (−21.3%)'));assert.equal(ids['fee-unit'],undefined);
assert.ok(ids['fee-schedule'].innerHTML.includes('paired-proposed fee-increase">$2.27'));assert.ok(ids['residential-fee-schedule'].innerHTML.includes('paired-proposed fee-decrease">$315.00'));let colorInput=useInput('Customer-Oriented High');colorInput.value=71;editUse(colorInput);assert.ok(ids['fee-schedule'].innerHTML.includes('paired-proposed fee-unchanged">$2.19'));assert.ok(visible('fee-schedule').includes('$2.19 | $2.19 | (0.0%)'));colorInput.value=90;editUse(colorInput);assert.ok(ids['fee-schedule'].innerHTML.includes('paired-proposed fee-decrease">$0.76'));assert.equal(useInput(colorInput.dataset.use),colorInput);ids.reset.onclick();
ids.period.value=5;ids.period.onchange();assert.equal(ids.current.textContent,'$32,984,844');assert.equal(ids.proposed.textContent,'$35,592,209');
ids['fee-sector'].value='Northeast';ids['fee-sector'].onchange();assert.ok(!visible('fee-schedule').includes('Not provided'));assert.ok(visible('fee-schedule').includes('$0.40 |'));
ids.zero.onclick();assert.equal(ids.proposed.textContent,'$118,640,696');ids.reset.onclick();assert.equal(ids.proposed.textContent,'$35,592,209');
control=ids['benefit-discounts'].children[0];num=control.children[1].children[0];num.value=101;num.oninput();assert.ok(ids.status.textContent.includes('between 0 and 100'));
for(const id of ['fee-schedule','residential-fee-schedule']){assert.equal((ids[id].innerHTML.match(/scope="col"/g)||[]).length,5);const tableRows=ids[id].innerHTML.split('<tbody>')[1].split('</tbody>')[0].match(/<tr[^>]*>[\s\S]*?<\/tr>/g);assert.equal(tableRows.length,8);for(const row of tableRows){assert.equal((row.match(/<td[ >]/g)||[]).length,5);assert.ok(!row.includes('/ sq ft'));assert.ok(!row.includes('/ dwelling'));}}
const revenueBeforeToggle=ids.proposed.textContent;ids['show-fee-change'].checked=false;ids['show-fee-change'].onchange();for(const id of ['fee-schedule','residential-fee-schedule']){assert.ok(!ids[id].innerHTML.includes('fee-change'));assert.ok(!ids[id].innerHTML.includes('| % change'));assert.ok(ids[id].innerHTML.includes('paired-proposed'));}assert.equal(ids.proposed.textContent,revenueBeforeToggle);ids['show-fee-change'].checked=true;ids['show-fee-change'].onchange();assert.ok(ids['fee-schedule'].innerHTML.includes('fee-change'));assert.ok(ids['residential-fee-schedule'].innerHTML.includes('fee-change'));assert.equal(ids.proposed.textContent,revenueBeforeToggle);
console.log('PASS: separate nonresidential/residential tables, dollar signs, percentage visibility checkbox, signed fee percentage changes, increase/decrease/unchanged fee colors, units outside cells, live discounts, revenue baseline, locations and periods. Browser visual rendering remains untested.');

const beforeMax=ids.proposed.textContent;
ids['show-fee-max'].checked=true;ids['show-fee-max'].onchange();assert.ok(visible('fee-schedule').includes('$19.29 | $2.51 | $5.79'));assert.ok(visible('residential-fee-schedule').includes('$1,993.00 | $285.00 | $597.90'));assert.equal(ids.proposed.textContent,beforeMax);
ids['show-fee-change'].checked=false;ids['show-fee-change'].onchange();assert.ok(ids['fee-schedule'].innerHTML.includes('paired-maximum'));assert.ok(!ids['fee-schedule'].innerHTML.includes('fee-change'));
for(const field of [...ids['fee-schedule'].children,...ids['residential-fee-schedule'].children]){field.value=100;editUse(field);}assert.ok(visible('fee-schedule').includes('$19.29 | $2.51 | $0.00'));assert.equal(ids.proposed.textContent,'$0');
ids.reset.onclick();
for(const sector of Object.keys(data.defaults.sector)){ids['fee-sector'].value=sector;ids['fee-sector'].onchange();for(const id of ['fee-schedule','residential-fee-schedule']){assert.ok(!visible(id).includes('Not provided'));assert.equal((ids[id].innerHTML.match(/paired-maximum/g)||[]).length,sector==='Core'?8:24);}}
ids['show-fee-max'].checked=false;ids['show-fee-max'].onchange();assert.ok(!ids['fee-schedule'].innerHTML.includes('paired-maximum'));assert.ok(!ids['residential-fee-schedule'].innerHTML.includes('paired-maximum'));
console.log('PASS: unchecked defaults, both independent visibility toggles, unchanged maximums when discounts change, every sector fully populated, complete maximum tables.');

assert.equal(ids['sector-discounts'].children.length,5);assert.equal(ids['benefit-discounts'].children.length,4);assert.ok(!body.includes('id="control-group"'));assert.ok(!body.includes('id="discount-controls"'));
ids['fee-sector'].value='Northeast';ids['fee-sector'].onchange();
for(const id of ['fee-schedule','residential-fee-schedule']){assert.equal(ids[id].children.length,8);assert.ok(ids[id].innerHTML.includes('<input'));assert.ok(ids[id].innerHTML.includes('discount-column'));}
const beforeResidential=ids.proposed.textContent,resInput=useInput('Residential (per housing unit) - Under 1,000');assert.equal(resInput.dataset.use,'Residential (per housing unit) - Under 1,000');resInput.value=100;editUse(resInput);assert.equal(ids.current.textContent,'$32,984,844');assert.notEqual(ids.proposed.textContent,beforeResidential);assert.ok(visible('residential-fee-schedule').includes('$285.00 | $0.00'));
const afterResidential=ids.proposed.textContent;resInput.value=101;editUse(resInput);assert.equal(ids.proposed.textContent,afterResidential);assert.ok(ids.status.textContent.includes('between 0 and 100'));resInput.value='';editUse(resInput);assert.equal(ids.proposed.textContent,afterResidential);
ids.reset.onclick();assert.equal(useInput('Residential (per housing unit) - Under 1,000').value,'70');assert.equal(ids['sector-discounts'].children[0].children[1].children[0].value,'0');
const benefitInput=ids['benefit-discounts'].children[1].children[1].children[0];assert.equal(ids['benefit-discounts'].children[1].children[0].textContent,'Infill');benefitInput.value=100;benefitInput.oninput();assert.ok(visible('fee-schedule').includes('$2.51 | $0.00'));assert.ok(visible('fee-schedule').includes('$2.97 | $6.59'));assert.ok(visible('residential-fee-schedule').includes('$285.00 | $0.00'));ids.reset.onclick();
console.log('PASS: geographic discounts in a separate tab and land-use discounts in fee tables, live cash and revenue updates, stable input nodes while typing, validation and reset.');

ids['fee-sector'].value='Northeast';ids['fee-sector'].onchange();ids['show-fee-change'].checked=true;ids['show-fee-change'].onchange();
const beforeMode=ids.proposed.textContent;assert.ok(visible('fee-schedule').includes('$2.51 | $5.79 | (+130.5%)'));
ids['change-dollar'].onclick();assert.equal(ids['change-dollar'].attributes['aria-pressed'],'true');assert.equal(ids['change-percent'].attributes['aria-pressed'],'false');assert.ok(visible('fee-schedule').includes('$2.51 | $5.79 | (+$3.28)'));assert.ok(visible('residential-fee-schedule').includes('$285.00 | $597.90 | (+$312.90)'));assert.ok(!ids['fee-schedule'].innerHTML.includes('(+130.5%)'));assert.equal(ids.proposed.textContent,beforeMode);
ids['change-percent'].onclick();assert.ok(visible('fee-schedule').includes('$2.51 | $5.79 | (+130.5%)'));assert.equal(ids.proposed.textContent,beforeMode);
ids['change-dollar'].onclick();ids['fee-sector'].value='Core';ids['fee-sector'].onchange();assert.ok(visible('residential-fee-schedule').includes('$400.00 | $315.00 | (−$85.00)'));
let equalInput=useInput('Customer-Oriented High');equalInput.value=71;editUse(equalInput);assert.ok(visible('fee-schedule').includes('$2.19 | $2.19 | ($0.00)'));
ids['show-fee-max'].checked=true;ids['show-fee-max'].onchange();assert.ok(visible('fee-schedule').includes('$7.56 | $2.19 | $2.19 | ($0.00)'));
const beforeHide=ids.proposed.textContent;ids['show-fee-change'].checked=false;ids['show-fee-change'].onchange();assert.ok(!ids['fee-schedule'].innerHTML.includes('fee-change'));assert.ok(ids['fee-schedule'].innerHTML.includes('paired-maximum'));ids['change-percent'].onclick();assert.ok(!ids['fee-schedule'].innerHTML.includes('fee-change'));ids['show-fee-change'].checked=true;ids['show-fee-change'].onchange();assert.ok(visible('fee-schedule').includes('$7.56 | $2.19 | $2.19 | (0.0%)'));assert.equal(ids.proposed.textContent,beforeHide);
console.log('PASS: change separators, percent/dollar mode switching, per-square-foot and per-dwelling dollar changes, positive/negative/zero values, unchecked visibility default and unchanged revenue from display controls.');

assert.ok(!body.includes('<aside>'));assert.ok(ids['fee-schedule'].innerHTML.includes('discount-cell'));assert.equal(ids['fee-panel'].hidden,false);assert.equal(ids['discount-panel'].hidden,true);assert.equal(ids['fee-filters'].hidden,false);assert.equal(ids['tab-fees'].attributes['aria-selected'],'true');
const tabRevenue=ids.proposed.textContent,tabSector=ids['fee-sector'].value,tabFees=ids['fee-schedule'].innerHTML;
ids['tab-discounts'].onclick();assert.equal(ids['discount-panel'].hidden,false);assert.equal(ids['fee-panel'].hidden,true);assert.equal(ids['fee-filters'].hidden,true);assert.equal(ids['tab-discounts'].attributes['aria-selected'],'true');assert.equal(ids.proposed.textContent,tabRevenue);
let tabInput=useInput('Customer-Oriented High');tabInput.value=90;editUse(tabInput);assert.equal(useInput(tabInput.dataset.use),tabInput);assert.notEqual(ids.proposed.textContent,tabRevenue);assert.notEqual(ids['fee-schedule'].innerHTML,tabFees);
const updatedRevenue=ids.proposed.textContent;ids['tab-fees'].onclick();assert.equal(ids['fee-panel'].hidden,false);assert.equal(ids['discount-panel'].hidden,true);assert.equal(ids['fee-sector'].value,tabSector);assert.equal(ids.proposed.textContent,updatedRevenue);assert.equal(ids['show-fee-change'].checked,true);assert.equal(ids['show-fee-max'].checked,true);assert.ok(visible('fee-schedule').includes('$2.19 | $0.76'));
let prevented=false;ids['tab-fees'].onkeydown({key:'ArrowRight',currentTarget:{id:'tab-fees'},preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(ids['discount-panel'].hidden,false);assert.equal(ids['tab-discounts'].focused,true);ids['tab-discounts'].onkeydown({key:'Home',currentTarget:{id:'tab-discounts'},preventDefault(){}});assert.equal(ids['fee-panel'].hidden,false);assert.equal(ids['tab-fees'].focused,true);
console.log('PASS: compact fee/discount/activity tabs, hidden-panel and filter state, keyboard navigation, retained settings and live revenue while editing discounts.');

ids.reset.onclick();ids.period.value=5;ids.period.onchange();ids['activity-sector'].value='Core';ids['activity-sector'].onchange();
const activityBase=ids.proposed.textContent,currentActivityBase=ids.current.textContent;
assert.ok(body.includes('>Past Development</button>'));assert.ok(!body.includes('Activity assumptions'));for(const id of ['activity-nonresidential','activity-residential'])for(const field of ids[id].children){const output=ids[field.dataset.annual];assert.equal(output.tag,'output');const schedule=data.feeSchedules.find(row=>[row.sector,row.benefit,row.use].join('|')===field.dataset.activity),quantity=data.defaults.activity[field.dataset.activity]/(schedule.residential?schedule.sampleSf:1);assert.equal(field.value,String(Number(quantity.toFixed(2))));assert.equal(output.textContent,new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(quantity/5));}

assert.equal(ids['unlock-activity'].checked,false);assert.equal(ids['restore-activity'].disabled,true);assert.ok(ids['activity-nonresidential'].children.every(input=>input.disabled));assert.ok(ids['activity-residential'].children.every(input=>input.disabled));
ids['tab-activity'].onclick();assert.equal(ids['activity-panel'].hidden,false);assert.equal(ids['fee-panel'].hidden,true);assert.equal(ids['discount-panel'].hidden,true);assert.equal(ids['fee-filters'].hidden,true);
let quantity=ids['activity-nonresidential'].children.find(input=>input.dataset.activity==='Core|Core|Customer-Oriented High');quantity.value=0;ids['activity-nonresidential'].oninput({target:quantity});assert.equal(ids.proposed.textContent,activityBase);assert.equal(ids.current.textContent,currentActivityBase);
ids['unlock-activity'].checked=true;ids['unlock-activity'].onchange();assert.equal(ids['restore-activity'].disabled,false);assert.ok(ids['activity-nonresidential'].children.every(input=>!input.disabled));quantity=ids['activity-nonresidential'].children.find(input=>input.dataset.activity==='Core|Core|Customer-Oriented High');quantity.value=0;ids['activity-nonresidential'].oninput({target:quantity});assert.notEqual(ids.proposed.textContent,activityBase);assert.notEqual(ids.current.textContent,currentActivityBase);assert.equal(ids['activity-nonresidential'].children.find(input=>input.dataset.activity===quantity.dataset.activity),quantity);
const quantityTotals=vm.runInContext('ImpactModel.total(ImpactModel.calculate(IMPACT_DATA,state))',context);assert.equal(ids.proposed.textContent,new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(quantityTotals.proposed));
assert.equal(ids[quantity.dataset.annual].textContent,'0');assert.equal(ids[quantity.dataset.annual].tag,'output');const afterQuantity=ids.proposed.textContent;for(const bad of ['-1','']){quantity.value=bad;ids['activity-nonresidential'].oninput({target:quantity});assert.equal(ids.proposed.textContent,afterQuantity);assert.ok(ids['activity-status'].textContent.includes('zero or more'));}quantity.value='0';
ids['unlock-activity'].checked=false;ids['unlock-activity'].onchange();assert.ok(ids['activity-nonresidential'].children.every(input=>input.disabled));assert.equal(ids.proposed.textContent,afterQuantity);ids['restore-activity'].onclick();assert.equal(ids.proposed.textContent,afterQuantity);
ids['unlock-activity'].checked=true;ids['unlock-activity'].onchange();ids['restore-activity'].onclick();assert.equal(ids.proposed.textContent,activityBase);assert.equal(ids.current.textContent,currentActivityBase);
ids['restore-activity'].onclick();let dwellingInput=ids['activity-residential'].children[0];dwellingInput.value=10;ids['activity-residential'].oninput({target:dwellingInput});assert.equal(ids[dwellingInput.dataset.annual].textContent,'2');assert.ok(!ids['activity-residential'].innerHTML.includes('modeled square footage'));assert.ok(!ids['activity-residential'].innerHTML.includes('activity-equivalent'));const dwellingRow=vm.runInContext('ImpactModel.calculate(IMPACT_DATA,state).find(r=>r.sector==="Core"&&r.use==="Residential (per housing unit) - Under 1,000")',context);assert.equal(dwellingRow.modeledUnits,10);assert.ok(Math.abs(dwellingRow.proposed-839*10*.3)<1e-8);assert.notEqual(ids.proposed.textContent,activityBase);
const savedFees=ids['fee-schedule'].innerHTML;ids['tab-fees'].onclick();assert.equal(ids['fee-panel'].hidden,false);assert.equal(ids['fee-schedule'].innerHTML,savedFees);assert.equal(ids['unlock-activity'].checked,true);ids['tab-activity'].onclick();assert.equal(dwellingInput.value,'10');
ids['activity-sector'].value='Northeast';ids['activity-sector'].onchange();assert.equal(ids['activity-nonresidential'].children.length,24);assert.equal(ids['activity-residential'].children.length,24);assert.ok(ids['activity-nonresidential'].children.every(input=>!input.disabled));
const emptyKey=vm.runInContext('ImpactModel.calculate(IMPACT_DATA,state).find(r=>r.sourceRow===null&&!r.residential&&r.sector==="Northeast").sector+"|"+ImpactModel.calculate(IMPACT_DATA,state).find(r=>r.sourceRow===null&&!r.residential&&r.sector==="Northeast").benefit+"|"+ImpactModel.calculate(IMPACT_DATA,state).find(r=>r.sourceRow===null&&!r.residential&&r.sector==="Northeast").use',context);const emptyInput=ids['activity-nonresidential'].children.find(input=>input.dataset.activity===emptyKey);assert.equal(emptyInput.value,'0');emptyInput.value=10000;ids['activity-nonresidential'].oninput({target:emptyInput});assert.equal(vm.runInContext('state.activity',context)[emptyKey],10000);
ids['tab-discounts'].onkeydown({key:'ArrowRight',currentTarget:{id:'tab-discounts'},preventDefault(){}});assert.equal(ids['activity-panel'].hidden,false);ids['tab-activity'].onkeydown({key:'ArrowRight',currentTarget:{id:'tab-activity'},preventDefault(){}});assert.equal(ids['revenue-panel'].hidden,false);ids['tab-revenue'].onkeydown({key:'ArrowRight',currentTarget:{id:'tab-revenue'},preventDefault(){}});assert.equal(ids['phase-panel'].hidden,false);ids['tab-phase'].onkeydown({key:'ArrowRight',currentTarget:{id:'tab-phase'},preventDefault(){}});assert.equal(ids['fee-panel'].hidden,false);
vm.runInContext('for(const key of Object.keys(state.activity))state.activity[key]=0;render();',context);assert.equal(ids.current.textContent,'$0');assert.equal(ids.proposed.textContent,'$0');assert.equal(ids.delta.textContent,'$0');ids['restore-activity'].onclick();assert.equal(ids.proposed.textContent,activityBase);
console.log('PASS: activity editor locked by default, guarded edits, both revenue structures updated, validation, stable input focus, restore, dwelling conversion, zero-history locations and zero activity.');

ids.reset.onclick();ids.period.value=5;ids.period.onchange();ids['revenue-sector'].value='all';ids['revenue-sector'].onchange();
assert.ok(body.includes('>Past Development</button>'));assert.ok(!body.includes('5-year past development'));assert.ok(body.includes('>Revenue</button>'));ids['tab-revenue'].onclick();assert.equal(ids['revenue-panel'].hidden,false);assert.equal(ids['activity-panel'].hidden,true);assert.equal(ids['fee-panel'].hidden,true);
const fmtRevenue=x=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(x);
const revenueCheck=(sector='all',benefit='all')=>{const rr=vm.runInContext('rows',context).filter(row=>(sector==='all'||row.sector===sector)&&(benefit==='all'||row.benefit===benefit));const totals={current:0,proposed:0};for(const [id,res] of [['revenue-nonresidential',false],['revenue-residential',true]]){const included=rr.filter(row=>row.phase2Rate!==null&&row.residential===res),t=included.reduce((sum,row)=>({current:sum.current+row.current,proposed:sum.proposed+row.proposed}),{current:0,proposed:0});const footer=ids[id].innerHTML.split('<tfoot>')[1].replace(/<[^>]*>/g,'');assert.ok(footer.includes(fmtRevenue(t.current)+' | '+fmtRevenue(t.proposed)));assert.ok(footer.includes(fmtRevenue(t.current/5)+' | '+fmtRevenue(t.proposed/5)));assert.equal((ids[id].innerHTML.split('<tbody>')[1].split('</tbody>')[0].match(/<tr>/g)||[]).length,8);assert.ok(ids[id].innerHTML.includes('5-year total'));assert.ok(ids[id].innerHTML.includes('Annualized'));assert.ok(!ids[id].innerHTML.includes('<input'));totals.current+=t.current;totals.proposed+=t.proposed;}return totals;};
let groupedTotal=revenueCheck();assert.equal(fmtRevenue(groupedTotal.current),ids.current.textContent);assert.equal(fmtRevenue(groupedTotal.proposed),ids.proposed.textContent);
const fixedRevenue=[ids['revenue-nonresidential'].innerHTML,ids['revenue-residential'].innerHTML];ids.period.value=1;ids.period.onchange();assert.equal(ids['revenue-nonresidential'].innerHTML,fixedRevenue[0]);assert.equal(ids['revenue-residential'].innerHTML,fixedRevenue[1]);ids.period.value=5;ids.period.onchange();
ids['revenue-sector'].value='Northeast';ids['revenue-sector'].onchange();revenueCheck('Northeast');ids['revenue-benefit'].value='Infill';ids['revenue-benefit'].onchange();revenueCheck('Northeast','Infill');assert.ok(!ids['revenue-benefit'].innerHTML.includes('<option>Core</option>'));
ids['revenue-sector'].value='Core';ids['revenue-sector'].onchange();assert.equal(ids['revenue-benefit'].value,'all');revenueCheck('Core');assert.ok(!ids['revenue-benefit'].innerHTML.includes('<option>Rural</option>'));
const beforeRevenueDiscount=ids['revenue-nonresidential'].innerHTML,revenueDiscount=useInput('Customer-Oriented High');revenueDiscount.value=100;editUse(revenueDiscount);assert.notEqual(ids['revenue-nonresidential'].innerHTML,beforeRevenueDiscount);const highRevenueRow=ids['revenue-nonresidential'].innerHTML.match(/<tr><td>Customer-Oriented High<\/td>([\s\S]*?)<\/tr>/)[1].replace(/<[^>]*>/g,'');assert.ok(highRevenueRow.includes('$121,322 | $0'));revenueCheck('Core');
ids['activity-sector'].value='Core';ids['activity-sector'].onchange();ids['unlock-activity'].checked=true;ids['unlock-activity'].onchange();const revenueDwelling=ids['activity-residential'].children[0];revenueDwelling.value=10;ids['activity-residential'].oninput({target:revenueDwelling});const dwellingRevenueRow=ids['revenue-residential'].innerHTML.match(/<tr><td>Under 1,000<\/td>([\s\S]*?)<\/tr>/)[1].replace(/<[^>]*>/g,'');assert.ok(dwellingRevenueRow.includes('$2,517'));assert.ok(dwellingRevenueRow.includes('$503'));revenueCheck('Core');
ids['tab-discounts'].onclick();ids['tab-revenue'].onclick();assert.equal(ids['revenue-sector'].value,'Core');assert.equal(ids['revenue-benefit'].value,'all');ids['tab-fees'].onkeydown({key:'End',currentTarget:{id:'tab-fees'},preventDefault(){}});assert.equal(ids['phase-panel'].hidden,false);assert.equal(ids['tab-phase'].focused,true);ids['tab-phase'].onkeydown({key:'Home',currentTarget:{id:'tab-revenue'},preventDefault(){}});assert.equal(ids['fee-panel'].hidden,false);
console.log('PASS: Revenue tab, both period breakdowns, residential and nonresidential subtotals reconcile to citywide totals, independent location filters, live discount and dwelling edits, fixed period columns and five-tab navigation.');

ids.reset.onclick();ids['phase-sector'].value='Northeast';ids['phase-sector'].onchange();ids['phase-benefit'].value='Infill';ids['phase-benefit'].onchange();ids['tab-phase'].onclick();assert.equal(ids['phase-panel'].hidden,false);assert.equal(ids['revenue-panel'].hidden,true);assert.equal(ids['fee-filters'].hidden,true);
const phaseRowsNow=()=>vm.runInContext('phaseRows()',context),timelineRow=(table,label)=>ids[table].innerHTML.match(new RegExp('<tr><td>'+label+'<\\/td>([\\s\\S]*?)<\\/tr>'))[1].replace(/<[^>]*>/g,'');
let phased=phaseRowsNow().find(r=>r.name==='Customer-Oriented High');assert.equal(phased.steps,6);assert.equal(phased.reachedYear,2033);assert.ok(timelineRow('phase-nonresidential','Customer-Oriented High').includes('62033$5.79$2.51'));
for(const id of ['phase-nonresidential','phase-residential']){assert.equal((ids[id].innerHTML.match(/scope="col"/g)||[]).length,15);const bodyRows=ids[id].innerHTML.split('<tbody>')[1].split('</tbody>')[0].match(/<tr>/g);assert.equal(bodyRows.length,8);assert.ok(ids[id].innerHTML.includes('2027'));assert.ok(ids[id].innerHTML.includes('2037'));assert.ok(!ids[id].innerHTML.includes('<input'));}
assert.ok(ids['phase-residential'].innerHTML.split('<tbody>')[1].startsWith('<tr><td>Under 1,000</td>'));
const phaseInitial=ids['phase-nonresidential'].innerHTML,stepInput=useInput('Customer-Oriented High');stepInput.value=0;editUse(stepInput);phased=phaseRowsNow().find(r=>r.name==='Customer-Oriented High');assert.equal(phased.steps,15);assert.equal(phased.reachedYear,2042);assert.ok(phased.schedule[10].value<phased.proposed);assert.notEqual(ids['phase-nonresidential'].innerHTML,phaseInitial);assert.ok(ids['phase-nonresidential'].innerHTML.includes('<td>2042</td>'));
ids['phase-sector'].value='Core';ids['phase-sector'].onchange();assert.equal(ids['phase-benefit'].value,'Core');ids.reset.onclick();phased=phaseRowsNow().find(r=>r.name==='Residential (per housing unit) - 1,000 to 1,499');assert.equal(phased.steps,0);assert.equal(phased.schedule[0].value,400);assert.ok(Math.abs(phased.schedule[1].value-315)<1e-8);assert.equal(phased.reachedYear,2028);
const sameInput=useInput('Customer-Oriented High');sameInput.value=71;editUse(sameInput);phased=phaseRowsNow().find(r=>r.name==='Customer-Oriented High');assert.equal(phased.steps,1);assert.equal(phased.reachedYear,2028);
const fixedPhase=ids['phase-residential'].innerHTML;ids['activity-sector'].value='Core';ids['activity-sector'].onchange();ids['unlock-activity'].checked=true;ids['unlock-activity'].onchange();const phaseDwelling=ids['activity-residential'].children[0];phaseDwelling.value=25;ids['activity-residential'].oninput({target:phaseDwelling});assert.equal(ids['phase-residential'].innerHTML,fixedPhase);
ids['tab-fees'].onkeydown({key:'End',currentTarget:{id:'tab-fees'},preventDefault(){}});assert.equal(ids['phase-panel'].hidden,false);assert.equal(ids['tab-phase'].focused,true);ids['tab-phase'].onkeydown({key:'ArrowRight',currentTarget:{id:'tab-phase'},preventDefault(){}});assert.equal(ids['fee-panel'].hidden,false);
ids.reset.onclick();console.log('PASS: Phase-in tab, separate 2027–2037 fee timelines, responsive discount steps, immediate decreases, beyond-window full-fee years, stable fees when quantities change, five-tab navigation.');


ids.reset.onclick();ids.period.value=1;ids.period.onchange();
const chartSummary=()=>vm.runInContext('revenueComposition(rows)',context);
let composition=chartSummary();assert.ok(Math.abs(composition.segments.reduce((sum,s)=>sum+s.value,0)-composition.proposed)<1e-7);assert.ok(Math.abs(composition.segments.reduce((sum,s)=>sum+s.share,0)-1)<1e-12);assert.equal(fmtRevenue(composition.current),ids.current.textContent);assert.equal(fmtRevenue(composition.proposed),ids.proposed.textContent);
assert.equal(composition.segments.filter(s=>s.name==='Residential').length,1);assert.equal((ids['benefit-revenue-charts'].innerHTML.match(/class="benefit-chart"/g)||[]).length,4);for(const benefit of Object.keys(data.defaults.benefit))assert.ok(ids['benefit-revenue-charts'].innerHTML.includes('<h4>'+benefit+'</h4>'));
const annualChart=composition.proposed,initialChart=ids['city-revenue-chart'].innerHTML,initialShares=composition.segments.map(s=>s.share);ids.period.value=5;ids.period.onchange();composition=chartSummary();assert.ok(Math.abs(composition.proposed-annualChart*5)<1e-7);assert.notEqual(ids['city-revenue-chart'].innerHTML,initialChart);composition.segments.forEach((s,i)=>assert.ok(Math.abs(s.share-initialShares[i])<1e-12));
const chartUse=useInput('Customer-Oriented High');chartUse.value=100;editUse(chartUse);composition=chartSummary();assert.equal(composition.segments.find(s=>s.name==='Customer-Oriented High').value,0);assert.ok(!ids['revenue-chart-legend'].innerHTML.includes('Customer-Oriented High'));
let chartBenefitTotal=0;for(const benefit of Object.keys(data.defaults.benefit)){const c=vm.runInContext('revenueComposition(rows.filter(r=>r.benefit==='+JSON.stringify(benefit)+'))',context);chartBenefitTotal+=c.proposed;assert.ok(Math.abs(c.segments.reduce((sum,s)=>sum+s.value,0)-c.proposed)<1e-7);}assert.ok(Math.abs(chartBenefitTotal-composition.proposed)<1e-7);
vm.runInContext('for(const key of Object.keys(state.activity))state.activity[key]=0;render();',context);composition=chartSummary();assert.equal(composition.current,0);assert.equal(composition.proposed,0);assert.ok(composition.segments.every(s=>s.share===0));assert.ok(!/NaN|Infinity/.test(ids['city-revenue-chart'].innerHTML+ids['benefit-revenue-charts'].innerHTML));ids.reset.onclick();
console.log('PASS: black current and stacked proposed revenue charts, complete benefit classes, native totals and percentage shares reconcile, residential grouping, period scaling, discount updates and zero activity.');

const hoverSegment=new Element('div');hoverSegment.dataset={chartCategory:'Residential',chartScope:'Infill',chartAmount:'$1,234,567',chartShare:'42.0%'};
ids['benefit-revenue-charts'].onpointerover({target:hoverSegment,clientX:1000,clientY:740});assert.equal(ids['revenue-chart-tooltip'].hidden,false);assert.ok(ids['revenue-chart-tooltip'].innerHTML.includes('Residential'));assert.ok(ids['revenue-chart-tooltip'].innerHTML.includes('42.0%'));assert.ok(ids['revenue-chart-tooltip'].innerHTML.includes('$1,234,567'));assert.equal(hoverSegment.attributes['aria-describedby'],'revenue-chart-tooltip');assert.ok(parseFloat(ids['revenue-chart-tooltip'].style.left)<=1024-230);assert.ok(parseFloat(ids['revenue-chart-tooltip'].style.top)+120<=768);
ids['benefit-revenue-charts'].onkeydown({key:'Escape'});assert.equal(ids['revenue-chart-tooltip'].hidden,true);assert.equal(hoverSegment.attributes['aria-describedby'],undefined);ids['benefit-revenue-charts'].onfocusin({target:hoverSegment});assert.equal(ids['revenue-chart-tooltip'].hidden,false);ids['benefit-revenue-charts'].onfocusout();assert.equal(ids['revenue-chart-tooltip'].hidden,true);
assert.ok(ids['city-revenue-chart'].innerHTML.includes('data-chart-category="Residential"'));assert.ok(ids['city-revenue-chart'].innerHTML.includes('data-chart-share='));assert.ok(!ids['city-revenue-chart'].innerHTML.includes('<span>42.0%</span>'));assert.ok(body.includes('<h2>Modeled Impact Fee Revenue</h2>'));console.log('PASS: category, share and dollar hover tooltips, viewport bounds, keyboard focus and Escape dismissal.');

ids.reset.onclick();ids.period.value=1;ids.period.onchange();
const checkDifferenceTable=()=>{const expected=vm.runInContext('rows',context);let currentSum=0,proposedSum=0;for(const benefit of Object.keys(data.defaults.benefit)){const t=expected.filter(r=>r.benefit===benefit).reduce((a,r)=>({current:a.current+r.current,proposed:a.proposed+r.proposed}),{current:0,proposed:0}),f=Number(ids.period.value)/5,delta=(t.proposed-t.current)*f,formatSigned=value=>Math.abs(value)<1e-10?fmtRevenue(0):(value>0?'+':'−')+fmtRevenue(Math.abs(value)),row=ids['benefit-revenue-summary'].innerHTML.split('<th scope="row">'+benefit+'</th>')[1].split('</tr>')[0];assert.ok(row.includes(fmtRevenue(t.current*f)));assert.ok(row.includes(fmtRevenue(t.proposed*f)));assert.ok(row.includes(formatSigned(delta)));currentSum+=t.current;proposedSum+=t.proposed;}assert.equal(fmtRevenue(currentSum*Number(ids.period.value)/5),ids.current.textContent);assert.equal(fmtRevenue(proposedSum*Number(ids.period.value)/5),ids.proposed.textContent);};
checkDifferenceTable();ids.period.value=5;ids.period.onchange();checkDifferenceTable();const diffDiscount=useInput('Customer-Oriented High');diffDiscount.value=100;editUse(diffDiscount);checkDifferenceTable();assert.ok(!body.includes('Difference (%)'));assert.ok(!body.includes('class="chart-change"'));console.log('PASS: unified Citywide and benefit-class difference table, both periods reconcile and live discounts update each row.');

ids.reset.onclick();const bulkNonres=ids['nonres-discount-range'],bulkRes=ids['res-discount-range'];assert.equal(bulkNonres.value,'70');assert.equal(bulkRes.value,'70');const bulkCurrent=ids.current.textContent;
bulkNonres.value=45;bulkNonres.oninput();assert.ok(ids['fee-schedule'].children.every(input=>input.value==='45'));assert.ok(ids['residential-fee-schedule'].children.every(input=>input.value==='70'));assert.equal(ids['nonres-discount-number'].value,'45');assert.equal(ids.current.textContent,bulkCurrent);checkDifferenceTable();
ids['res-discount-number'].value=60;ids['res-discount-number'].oninput();assert.ok(ids['residential-fee-schedule'].children.every(input=>input.value==='60'));assert.ok(ids['fee-schedule'].children.every(input=>input.value==='45'));assert.equal(bulkRes.value,'60');
let bulkOverride=useInput('Customer-Oriented High');bulkOverride.value=65;editUse(bulkOverride);assert.equal(ids['nonres-discount-number'].value,'');assert.equal(ids['nonres-discount-number'].attributes.placeholder,'Mixed');assert.equal(bulkNonres.attributes['aria-valuetext'],'Mixed discounts');assert.equal(useInput('Industrial').value,'45');assert.equal(bulkRes.value,'60');
const beforeBadBulk=ids.proposed.textContent;ids['nonres-discount-number'].value=101;ids['nonres-discount-number'].oninput();assert.equal(ids.proposed.textContent,beforeBadBulk);bulkNonres.value=100;bulkNonres.oninput();assert.ok(ids['fee-schedule'].children.every(input=>input.value==='100'));assert.ok(vm.runInContext('rows.filter(r=>r.phase2Rate!==null&&!r.residential).every(r=>r.proposed===0)',context));assert.ok(vm.runInContext('rows.some(r=>r.residential&&r.proposed>0)',context));bulkRes.value=100;bulkRes.oninput();assert.equal(ids.proposed.textContent,'$0');ids.reset.onclick();assert.equal(bulkNonres.value,'70');assert.equal(bulkRes.value,'70');ids.zero.onclick();assert.equal(bulkNonres.value,'0');assert.equal(bulkRes.value,'0');ids.reset.onclick();console.log('PASS: independent residential/nonresidential bulk sliders and inputs, individual overrides and mixed state, validation, revenue updates and reset.');

ids.reset.onclick();assert.equal(ids.delta.className,'difference-positive');ids['nonres-discount-range'].value=100;ids['nonres-discount-range'].oninput();ids['res-discount-range'].value=100;ids['res-discount-range'].oninput();assert.equal(ids.delta.className,'difference-negative');vm.runInContext('for(const key of Object.keys(state.activity))state.activity[key]=0;render();',context);assert.equal(ids.delta.className,'difference-zero');assert.equal(ids.delta.textContent,'$0');ids.reset.onclick();console.log('PASS: Citywide difference switches between positive, negative and zero styles.');
